# generated by Git for Windows
test -f ~/.profile && . ~/.profile
test -f ~/.bashrc && . ~/.bashrc

export PATH=$PATH:/c/payara/installations/payara-4.1.2.181/payara41/bin
export APPS_HOME_FOLDER="/c/Users/rop61488/Documents/Apps"
export PAYARA_DOMAINS_DIR="/c/payara/domains"

source ~/.bash_aliases
